# pokemon-colorscripts
# Autogenerated from man page /usr/share/man/man1/pokemon-colorscripts.1.gz
complete -c pokemon-colorscripts -s h -l help -d 'Print help'
complete -c pokemon-colorscripts -s l -l list -d 'List all available pokemon'
complete -c pokemon-colorscripts -s r -l random -d 'Select a pokemon at random and print it out'
complete -c pokemon-colorscripts -s n -l name -d 'Select a specific pokemon to print out by name'
complete -c pokemon-colorscripts -s f -l form -d 'Display an alternate form of the pokemon'
complete -c pokemon-colorscripts -s s -l shiny -d 'Show the shiny version of the pokemon instead'
complete -c pokemon-colorscripts -s b -l big -d 'Show a larger size sprite'

