# wayvncctl
# Autogenerated from man page /usr/share/man/man1/wayvncctl.1.gz
complete -c wayvncctl -s w -l wait -d 'Wait for wayvnc to start up if it\'s not already running.  Default: Exit'
complete -c wayvncctl -s r -l reconnect -d 'If disconnected while waiting for events, wait for wayvnc to restart and'
complete -c wayvncctl -s j -l json -d 'Produce json output to stdout'
complete -c wayvncctl -s V -l version -d 'Show version info'
complete -c wayvncctl -s v -l verbose -d 'Be more verbose'
complete -c wayvncctl -s h -l help -d 'Get help about the wayvncctl command itself (lists these options).  Does'

