# wayvnc
# Autogenerated from man page /usr/share/man/man1/wayvnc.1.gz
complete -c wayvnc -s g -l gpu -d 'Enable features that require GPU'
complete -c wayvnc -s o -l output -d 'Select output to capture'
complete -c wayvnc -s k -l keyboard -d 'Select keyboard layout.  The variant can be appended if needed'
complete -c wayvnc -s s -l seat -d 'Select seat by name'
complete -c wayvnc -s S -l socket -d 'Set wayvnc control socket path.  Default: $XDG_RUNTIME_DIR/wayvncctl'
complete -c wayvnc -s r -l render-cursor -d 'Enable overlay cursor rendering'
complete -c wayvnc -s f -l max-fps -d 'Set the rate limit (default 30)'
complete -c wayvnc -s p -l show-performance -d 'Show performance counters'
complete -c wayvnc -s u -l unix-socket -d 'Create a UNIX domain socket instead of TCP, treating the address as a'
complete -c wayvnc -s d -l disable-input -d 'Disable all remote input.  This allows using wayvnc without compositor'
complete -c wayvnc -s V -l version -d 'Show version info'
complete -c wayvnc -s v -l verbose -d 'Be more verbose.  Same as setting `--log-level=info`'
complete -c wayvnc -s w -l websocket -d 'Create a websocket'
complete -c wayvnc -s L -l log-level -d 'Set log level.  The levels are: error, warning, info, debug, trace and'
complete -c wayvnc -s h -l help -d 'Get help'

