# zerotier-one
# Autogenerated from man page /usr/share/man/man8/zerotier-one.8.gz
complete -c zerotier-one -s h -d 'Display help.  o 2'
complete -c zerotier-one -s v -d 'Display ZeroTier One version.  o 2'
complete -c zerotier-one -s U -d 'Skip privilege check and allow to be run by non-privileged user'
complete -c zerotier-one -o 'p<port>' -d 'Specify a different primary port.  If this is not given the default is 9993'
complete -c zerotier-one -s d -d 'Fork and run as a daemon.  o 2'
complete -c zerotier-one -s i -d 'Invoke the zerotier-idtool personality, in which case the binary behaves like…'
complete -c zerotier-one -s q -d 'Invoke the zerotier-cli personality, in which case the binary behaves like ze…'

